### ISSUE TITLE
DashError: An unexpected result was received, this is usually because the authentication is invalid

### ISSUE THREAD

**Issue by Jerbyyy0** [PyronDev/dash#1]
"DashError: An unexpected result was received, this is usually because the authentication is invalid" is still existing and my console will be spammed with "Credentials refreshed successfully". (Auto reload isnt working)

**Comment by titushm** [comment]
Will be rewritten soon

**Comment by titushm** [comment]
@JerbyYT should be fixed in release 1.1.3
